# Método SIMPLEX

In [2]:
import numpy as np
import sys

### Função para printar a matriz

In [5]:
def print_matriz(matriz, qtd_linha, qtd_coluna):
    for i in range(qtd_linha):
        for j in range(qtd_coluna):
            print(matriz[i][j], end=" ")

        print()

### Pegando quantidade de variáveis

In [8]:
qtd_var_obj = int(input("Quantas variáveis possui a função objetivo? \n"))

Quantas variáveis possui a função objetivo? 
 3


In [10]:
qtd_res_des = int(input("Quantas restrições com desigualdade? \n"))

Quantas restrições com desigualdade? 
 3


In [12]:
lista_var = []

for i in range(qtd_var_obj+1, (qtd_var_obj + qtd_res_des)+1):
    lista_var.append(i)

lista_var = np.array(lista_var)

lista_var

array([4, 5, 6])

### Pegando matriz

In [15]:
mat = []

while True:
    linha = input("Digite uma linha (ou \"p\" para parar) \n")

    if linha.lower() == "p": #condição de parada
        break

    linha = linha.split()
    
    try:
        linha = [float(x) for x in linha] #cast para float
    except ValueError:
        print("Insira apenas números ou \"p\" para parar \n")
        continue

    mat.append(linha)

Digite uma linha (ou "p" para parar) 
 2 3 1 1 0 0 5
Digite uma linha (ou "p" para parar) 
 4 2 2 0 1 0 11
Digite uma linha (ou "p" para parar) 
 3 2 2 0 0 1 8
Digite uma linha (ou "p" para parar) 
 -5 -4 -3 0 0 0 0
Digite uma linha (ou "p" para parar) 
 p


In [17]:
matriz = np.array(mat)

In [19]:
matriz

array([[ 2.,  3.,  1.,  1.,  0.,  0.,  5.],
       [ 4.,  2.,  2.,  0.,  1.,  0., 11.],
       [ 3.,  2.,  2.,  0.,  0.,  1.,  8.],
       [-5., -4., -3.,  0.,  0.,  0.,  0.]])

### Realizando cálculos

In [22]:
qtd_linha = len(matriz)
qtd_linha

4

In [24]:
qtd_coluna = len(matriz[0])

qtd_coluna

7

In [26]:
ultima_linha = matriz[qtd_linha-1]

ultima_linha

array([-5., -4., -3.,  0.,  0.,  0.,  0.])

### Código para Maximização

In [29]:
while len([*filter(lambda x: x < 0, ultima_linha)]) > 0:
    menor = min(ultima_linha)
    
    for i in range(qtd_coluna): 
        if ultima_linha[i] == menor:
            coluna_pivo = i
    
    aux_m = 2 * sys.maxsize + 1
    linha_pivo = -1
        
    for i in range(qtd_linha-1):
        e = matriz[i][coluna_pivo]
        
        if e != 0:
            f = matriz[i][qtd_coluna-1] / e
        
            if f < aux_m:
                aux_m = f
                linha_pivo = i
                    
    lista_var[linha_pivo] = coluna_pivo + 1
    
    matriz[linha_pivo] = matriz[linha_pivo] / matriz[linha_pivo][coluna_pivo]
    
    for i in range(qtd_linha):
        if i != linha_pivo:
            matriz[i] = matriz[i] - (matriz[i][coluna_pivo] * matriz[linha_pivo])

In [31]:
#print(lista_var)
print_matriz(matriz, qtd_linha, qtd_coluna)

1.0 4.0 0.0 2.0 0.0 -1.0 2.0 
0.0 -4.0 0.0 -2.0 1.0 0.0 1.0 
0.0 -5.0 1.0 -3.0 0.0 2.0 1.0 
0.0 1.0 0.0 1.0 0.0 1.0 13.0 


In [33]:
for i in range(len(lista_var)):
    print(f"x{lista_var[i]} = {matriz[i][qtd_coluna-1]}")

print()
print(f"z = {matriz[qtd_linha-1][qtd_coluna-1]}")

x1 = 2.0
x5 = 1.0
x3 = 1.0

z = 13.0
